### PR TITLE
feat: add required keys to components module

### PR DESCRIPTION
**Pull request by laraujo7**

### CODE REVIEW

**Review by nelsonmestevao — APPROVED** [review]

**Review by filipecabaco — COMMENTED** [review]
Nice!!! Do a quick change on the petstore specification used in tests to add a required key to properly test things around

**Comment by laraujo7** [comment]
I didn't really understand @filipecabaco 😕

**Comment by filipecabaco** [comment]
My bad 😅

Change the https://github.com/marmelasoft/openapi_codegen/blob/main/test/support/fixtures/openapi_petstore.json file to have a required field so our tests can properly test this feature

**Comment by laraujo7** [comment]
Pet already had required keys but I've also added for the user :muscle:

**Review by filipecabaco — APPROVED** [review]

**Comment by filipecabaco** [comment]
👏🚀

**Pull request merged**
